### ISSUE TITLE
[Maintenance] Install RuboCop (Ruby Style Analyzer)

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#564]
At the moment we have different ruby code syntax and styles (e.g. `:variable => 'string'` vs. `variable: 'string'`) in wheelmap. Using [rubocop](https://github.com/bbatsov/rubocop) could help us to bring our different styles aligned and increase our code quality by refactoring. Since establishing this gem may also cause a lot of error alerts (travis), we should calculcate a bit of time for this enhancement.

**Comment by Hoverbear** [comment]
I'll tackle this!

**Comment by 1000miles** [comment]
@Hoverbear Thanks, happy exploring! :)

**Comment by Hoverbear** [comment]
So we probably want the defaults with the exception of:


Globally:

```yaml
# This is a slightly unnecessary limit.
Metrics/LineLength:
    Enabled: false
```

On `spec/*`:

```yaml
Metrics/BlockLength:
  Enabled: false
```

We may also want to consider:

```yaml
# This alerts on what is otherwise very understandable code.
Style/GuardClause:
  Enabled: false
```
