### ISSUE TITLE
URL are broken in french locale

### ISSUE THREAD

**Issue by pyrog** [sozialhelden/wheelmap#663]
In [/config/locales/fr/relaunch.yml#L152](http://github.com/sozialhelden/wheelmap/blob/master/config/locales/fr/relaunch.yml#L152)
```yml
      show:
        title: Aperçu
        text_html: "Vous pouvez parcourir notre <a href=\\\"http://news.wheelmap.org/en/\\\">Blog</a>"
```

Should be:
```yml
      show:
        title: Aperçu
        text_html: "Vous pouvez parcourir notre <a href=\"http://news.wheelmap.org/en/\">Blog</a>"
```
